services:
  - type: web
    name: kitchenit-backend
    runtime: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false 
      - key: SPOONACULAR_API_KEY
        sync: false